
services:

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - "8092:8080"

  postgres:
    image: postgres:15
    container_name: bank-postgres
    restart: on-failure
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"

  redis:
    image: redis:7-alpine
    container_name: bank-redis
    restart: on-failure
    ports:
      - "6379:6379"

  service-container:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9080:9080"
    restart: on-failure
    depends_on:
      - postgres